#!/bin/sh
set -eu

exec /Users/trafficsign/.local/bin/uvx \
  --refresh-package chronovisor \
  --from git+ssh://git@github.com/trafficsign/chronovisor \
  chronovisor-librarian \
  --root /Users/trafficsign/.chronovisor \
  --review-collection-queue \
  --limit "${CHRONOVISOR_LIBRARIAN_REVIEW_LIMIT:-5}" \
  --review-model "${CHRONOVISOR_LIBRARIAN_REVIEW_MODEL:-gemma4:26b}" \
  --json
