#!/bin/sh
set -eu

PROJECT_DIR="/Users/trafficsign/projects/personal/chronovisor"
RUNTIME_SOURCE="${CHRONOVISOR_RUNTIME_SOURCE:-git+ssh://git@github.com/trafficsign/chronovisor}"
PATH="/Users/trafficsign/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/sbin:/usr/sbin:/sbin"
export PATH CHRONOVISOR_REPO_ROOT="${CHRONOVISOR_REPO_ROOT:-$PROJECT_DIR}"

exec uvx \
  --refresh-package chronovisor \
  --with "torch==2.13.0" \
  --with "transformers==5.14.1" \
  --with "sentence-transformers==5.6.1" \
  --with "usearch>=2.20.0" \
  --from "$RUNTIME_SOURCE" \
  chronovisor-semantic-service "$@"
