const els = {
  statePill: document.getElementById("state-pill"),
  stateText: document.getElementById("state-text"),
  pending: document.getElementById("pending-value"),
  pendingSub: document.getElementById("pending-sub"),
  held: document.getElementById("held-value"),
  heldSub: document.getElementById("held-sub"),
  stage: document.getElementById("stage-value"),
  raw: document.getElementById("raw-value"),
  batch: document.getElementById("batch-value"),
  batchSub: document.getElementById("batch-sub"),
  ollama: document.getElementById("ollama-value"),
  ollamaSub: document.getElementById("ollama-sub"),
  processingPanel: document.getElementById("processing-panel"),
  processingConnection: document.getElementById("processing-connection"),
  processingLanes: document.getElementById("processing-lanes"),
  lanShareButton: document.getElementById("lan-share-button"),
  decisionTracePanel: document.getElementById("decision-trace-panel"),
  decisionTraceHarness: document.getElementById("decision-trace-harness"),
  workOverview: document.getElementById("work-overview"),
  workSummary: document.getElementById("work-summary"),
  workUpdated: document.getElementById("work-updated"),
  workDetail: document.getElementById("work-detail"),
  decisionElapsed: document.getElementById("decision-elapsed"),
  decisionContext: document.getElementById("decision-context"),
  decisionBadge: document.getElementById("decision-badge"),
  decisionModelCalls: document.getElementById("decision-model-calls"),
  decisionQuorum: document.getElementById("decision-quorum"),
  decisionMutation: document.getElementById("decision-mutation"),
  decisionOutcomeReason: document.getElementById("decision-outcome-reason"),
  decisionOutcomeData: document.getElementById("decision-outcome-data"),
  decisionOutcomeNext: document.getElementById("decision-outcome-next"),
  decisionTraceCaption: document.getElementById("decision-trace-caption"),
  decisionOverallSteps: document.getElementById("decision-overall-steps"),
  decisionTransitionState: document.getElementById("decision-transition-state"),
  decisionTransitionDetail: document.getElementById("decision-transition-detail"),
  decisionTransitionFeed: document.getElementById("decision-transition-feed"),
  decisionEventCount: document.getElementById("decision-event-count"),
  decisionGenerationMeter: document.getElementById("decision-generation-meter"),
  decisionGenerationTrack: document.getElementById("decision-generation-track"),
  decisionGenerationFill: document.getElementById("decision-generation-fill"),
  decisionGenerationModel: document.getElementById("decision-generation-model"),
  decisionGenerationReasoning: document.getElementById("decision-generation-reasoning"),
  decisionGenerationTokens: document.getElementById("decision-generation-tokens"),
  decisionGenerationSpeed: document.getElementById("decision-generation-speed"),
  decisionGenerationTime: document.getElementById("decision-generation-time"),
  decisionLanes: document.querySelectorAll("[data-decision-lane]"),
  currentRaw: document.getElementById("current-raw"),
  currentOp: document.getElementById("current-op"),
  llmSignal: document.getElementById("llm-signal"),
  llmState: document.getElementById("llm-state"),
  llmAge: document.getElementById("llm-age"),
  llmTarget: document.getElementById("llm-target"),
  llmStats: document.getElementById("llm-stats"),
  llmSparkline: document.getElementById("llm-sparkline"),
  localConsensus: document.getElementById("local-consensus"),
  frontierRepair: document.getElementById("frontier-repair"),
  currentJob: document.getElementById("current-job"),
  lastSuccess: document.getElementById("last-success"),
  selfHealPanel: document.getElementById("self-heal-panel"),
  selfHealCaption: document.getElementById("self-heal-caption"),
  selfHealState: document.getElementById("self-heal-state"),
  selfHealLatest: document.getElementById("self-heal-latest"),
  selfHealDetail: document.getElementById("self-heal-detail"),
  selfHealLastCheck: document.getElementById("self-heal-last-check"),
  selfHealLastStatus: document.getElementById("self-heal-last-status"),
  selfHealPendingPackets: document.getElementById("self-heal-pending-packets"),
  selfHealPacketTotal: document.getElementById("self-heal-packet-total"),
  selfHealFrontierCard: document.getElementById("self-heal-frontier-card"),
  selfHealFrontierState: document.getElementById("self-heal-frontier-state"),
  selfHealFrontierDetail: document.getElementById("self-heal-frontier-detail"),
  selfHealCounts: document.getElementById("self-heal-counts"),
  selfHealFeed: document.getElementById("self-heal-feed"),
  trendCaption: document.getElementById("trend-caption"),
  pendingCurrent: document.getElementById("pending-current"),
  pendingDelta: document.getElementById("pending-delta"),
  pendingRate: document.getElementById("pending-rate"),
  pendingDeferred: document.getElementById("pending-deferred"),
  pendingEta: document.getElementById("pending-eta"),
  batchCaption: document.getElementById("batch-caption"),
  batchOk: document.getElementById("batch-ok"),
  batchDeferred: document.getElementById("batch-deferred"),
  batchContinued: document.getElementById("batch-continued"),
  batchFailed: document.getElementById("batch-failed"),
  batchDuration: document.getElementById("batch-duration"),
  saveTotal: document.getElementById("save-total"),
  saveProcessed: document.getElementById("save-processed"),
  savePages: document.getElementById("save-pages"),
  saveFailed: document.getElementById("save-failed"),
  saveMonths: document.getElementById("save-months"),
  saveHeatmap: document.getElementById("save-heatmap"),
  saveDetail: document.getElementById("save-detail"),
  saveFeed: document.getElementById("save-feed"),
  saveModeButtons: document.querySelectorAll("[data-save-mode]"),
  knowledgeCaption: document.getElementById("knowledge-caption"),
  knowledgeChart: document.getElementById("knowledge-chart"),
  knowledgeTotal: document.getElementById("knowledge-total"),
  knowledgeBars: document.getElementById("knowledge-bars"),
  knowledgePages: document.getElementById("knowledge-pages"),
  knowledgeSize: document.getElementById("knowledge-size"),
  knowledgeCategories: document.getElementById("knowledge-categories"),
  knowledgeModeButtons: document.querySelectorAll("[data-knowledge-mode]"),
  librarianPanel: document.getElementById("librarian-panel"),
  librarianState: document.getElementById("librarian-state"),
  librarianHeadline: document.getElementById("librarian-headline"),
  librarianDetail: document.getElementById("librarian-detail"),
  librarianGeneration: document.getElementById("librarian-generation"),
  librarianSweptGeneration: document.getElementById("librarian-swept-generation"),
  librarianUid: document.getElementById("librarian-uid"),
  librarianUidBar: document.getElementById("librarian-uid-bar"),
  librarianClassification: document.getElementById("librarian-classification"),
  librarianClassificationBar: document.getElementById("librarian-classification-bar"),
  librarianLinks: document.getElementById("librarian-links"),
  librarianLinksBar: document.getElementById("librarian-links-bar"),
  librarianMigration: document.getElementById("librarian-migration"),
  librarianMigrationBar: document.getElementById("librarian-migration-bar"),
  librarianSweep: document.getElementById("librarian-sweep"),
  librarianSweepBar: document.getElementById("librarian-sweep-bar"),
  librarianAuthority: document.getElementById("librarian-authority"),
  librarianQuality: document.getElementById("librarian-quality"),
  librarianCollectionCount: document.getElementById("librarian-collection-count"),
  librarianAssignment: document.getElementById("librarian-assignment"),
  librarianCrosswalk: document.getElementById("librarian-crosswalk"),
  librarianTopShare: document.getElementById("librarian-top-share"),
  librarianReviewQueue: document.getElementById("librarian-review-queue"),
  librarianSplitProposals: document.getElementById("librarian-split-proposals"),
  librarianRollout: document.getElementById("librarian-rollout"),
  librarianSoak: document.getElementById("librarian-soak"),
  librarianRecovery: document.getElementById("librarian-recovery"),
  librarianEvidenceStatus: document.getElementById("librarian-evidence-status"),
  librarianEvidenceFixture: document.getElementById("librarian-evidence-fixture"),
  librarianEvidenceRecall: document.getElementById("librarian-evidence-recall"),
  librarianEvidenceExternal: document.getElementById("librarian-evidence-external"),
  librarianEvidenceHold: document.getElementById("librarian-evidence-hold"),
  librarianEvidenceResource: document.getElementById("librarian-evidence-resource"),
  librarianEvidenceStorage: document.getElementById("librarian-evidence-storage"),
  librarianEvidenceAuthority: document.getElementById("librarian-evidence-authority"),
  librarianEvidenceUpdate: document.getElementById("librarian-evidence-update"),
  librarianQueue: document.getElementById("librarian-queue"),
  librarianFlow: document.getElementById("librarian-flow"),
  librarianReceipts: document.getElementById("librarian-receipts"),
  healthCaption: document.getElementById("health-caption"),
  healthSummaryCoverage: document.getElementById("health-summary-coverage"),
  healthCapture: document.getElementById("health-capture"),
  healthReadback: document.getElementById("health-readback"),
  healthSensitive: document.getElementById("health-sensitive"),
  healthDupes: document.getElementById("health-dupes"),
  healthGolden: document.getElementById("health-golden"),
  healthGoldenSet: document.getElementById("health-golden-set"),
  healthRetention: document.getElementById("health-retention"),
  healthDistill: document.getElementById("health-distill"),
  healthReplay: document.getElementById("health-replay"),
  healthDeadman: document.getElementById("health-deadman"),
  healthQuality: document.getElementById("health-quality"),
  healthHolds: document.getElementById("health-holds"),
  healthProvisional: document.getElementById("health-provisional"),
  healthRecallDistillation: document.getElementById("health-recall-distillation"),
  healthRecallDistillationDetail: document.getElementById("health-recall-distillation-detail"),
  healthLedger: document.getElementById("health-ledger"),
  healthResearchRuns: document.getElementById("health-research-runs"),
  healthResearchClaims: document.getElementById("health-research-claims"),
  healthResearchTrace: document.getElementById("health-research-trace"),
  modelCaption: document.getElementById("model-caption"),
  modelInstalled: document.getElementById("model-installed"),
  modelLoaded: document.getElementById("model-loaded"),
  modelConfigured: document.getElementById("model-configured"),
  modelMissing: document.getElementById("model-missing"),
  modelFailureFeed: document.getElementById("model-failure-feed"),
  modelGrid: document.getElementById("model-grid"),
  modelLabCaption: document.getElementById("model-lab-caption"),
  modelLabRoles: document.getElementById("model-lab-roles"),
  modelLabReplays: document.getElementById("model-lab-replays"),
  modelLabCandidates: document.getElementById("model-lab-candidates"),
  modelLabCanaries: document.getElementById("model-lab-canaries"),
  modelLabGrid: document.getElementById("model-lab-grid"),
  recallPanel: document.getElementById("recall-panel"),
  recallCaption: document.getElementById("recall-caption"),
  recallR3: document.getElementById("recall-r3"),
  recallWaste: document.getElementById("recall-waste"),
  recallP50: document.getElementById("recall-p50"),
  recallP95: document.getElementById("recall-p95"),
  recallCounts: document.getElementById("recall-counts"),
  recallFieldSummary: document.getElementById("recall-field-summary"),
  recallFieldState: document.getElementById("recall-field-state"),
  recallFieldCounts: document.getElementById("recall-field-counts"),
  recallFieldQuality: document.getElementById("recall-field-quality"),
  recallCalibration: document.getElementById("recall-calibration"),
  recallFeed: document.getElementById("recall-feed"),
  recallLabPanel: document.getElementById("recall-lab-panel"),
  recallLabCaption: document.getElementById("recall-lab-caption"),
  recallLabState: document.getElementById("recall-lab-state"),
  recallLabLatest: document.getElementById("recall-lab-latest"),
  recallLabDetail: document.getElementById("recall-lab-detail"),
  recallLabActive: document.getElementById("recall-lab-active"),
  recallLabDev: document.getElementById("recall-lab-dev"),
  recallLabHoldout: document.getElementById("recall-lab-holdout"),
  recallLabModels: document.getElementById("recall-lab-models"),
  recallLabPolicy: document.getElementById("recall-lab-policy"),
  recallLabFeed: document.getElementById("recall-lab-feed"),
  eventFeed: document.getElementById("event-feed"),
  pendingChart: document.getElementById("pending-chart"),
  saveLoadTooltip: document.getElementById("save-load-tooltip"),
  batchChart: document.getElementById("batch-chart"),
};

const llmSignalHistory = {
  key: null,
  lastChars: null,
  lastSeenMs: null,
  rates: Array(32).fill(0),
};

const WORK_STAGE_ALIASES = {
  idle: "idle",
  queued: "raw",
  raw: "raw",
  triage: "triage",
  classify: "triage",
  generate: "generate",
  generating: "generate",
  llm: "generate",
  review: "review",
  apply: "apply",
  applying: "apply",
  write: "apply",
  index: "index",
  indexing: "index",
  complete: "index",
  done: "index",
};

const STAGE_METRIC_LABELS = {
  "local-consensus-review": "Local review",
  "local-regenerate": "Local retry",
  "frontier-review": "Consensus review",
  "frontier-regenerate": "Consensus retry",
  authorization: "Authorize",
};

let saveHistoryMode = "daily";
let latestSaveHistory = null;
let selectedSaveDate = null;
let knowledgeMixMode = "size";
let latestKnowledgeMix = null;
let saveLoadHitRegions = [];
let latestRenderedStatus = null;

const KNOWLEDGE_COLORS = [
  "#828fff",
  "#3dd68c",
  "#e8b04b",
  "#c983f7",
  "#ff7e79",
  "#56a8ff",
  "#e0cd6d",
  "#4fc8b4",
];
